# Generated by Django 3.1.7 on 2021-03-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(choices=[('noun', 'English'), ('verb', 'Tamil'), ('adverb', 'German'), ('adjective', 'Adjective')], max_length=10)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictApp.headword')),
            ],
        ),
    ]
