# Generated by Django 3.1.7 on 2021-03-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_auto_20210301_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='part_name',
            new_name='pos',
        ),
        migrations.AlterField(
            model_name='meaning',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_meaning', to='dictApp.pos'),
        ),
        migrations.AlterUniqueTogether(
            name='pos',
            unique_together={('word', 'pos')},
        ),
    ]
