# Generated by Django 3.1.7 on 2021-03-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0003_auto_20210301_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='pos',
            new_name='part_of_speech',
        ),
        migrations.AlterField(
            model_name='pos',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dictApp.headword'),
        ),
        migrations.AlterUniqueTogether(
            name='pos',
            unique_together={('word', 'part_of_speech')},
        ),
    ]
