# Generated by Django 3.1.7 on 2021-03-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0004_auto_20210301_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_meanings', to='dictApp.pos'),
        ),
    ]
